### ISSUE TITLE
Fix Gesture. 

### ISSUE THREAD

**Issue by joshmarinacci** [joshmarinacci/jsconfeu-builder#19]
Currently you can accidentally press the back button and lose your work on the editor page. We must at least block this if you have unsaved work and warn the user

**Comment by tschneidereit** [comment]
We can either just always warn, or expose a signal from Wasm Studio warning about this. Wasm Studio itself shows a confirm dialog in this case, but can't do so if the top-level window navigates. We could send a postMessage whenever the project's state changes to either allow or block navigation, if that seems better.
