### ISSUE TITLE
Please configure outgoing webhook for Netlify

### ISSUE THREAD

**Issue by gozer** [joshmarinacci/jsconfeu-builder#35]
Hi, in the process of moving the public facing website http://experiencethearch.mozilla.org/ to a different static site provider, namely, Netlify.

For the builds to get triggered on git pushes, it's important to enable the right webhook for Netlify, and I can't configure that on your behalf.

So you can either make me an admin for this repo and I'll do it, otherwise, please setup a webhook like this:

Go to https://github.com/mozilla/arch-website/settings/hooks/new to configure a new webhook

The URL should be https://api.netlify.com/hooks/github
Content-type: application/json

And no need to send evertyhing, one can just select:
 * Pull Requests
 * Pushes
* Branch or tag deletion

Thanks!

**Comment by joshmarinacci** [comment]
I just made you admin.

**Comment by gozer** [comment]
Excellent! Thank you!
